# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Bright Canopy Blog
tagline:          SL Anywhere
url:              http://www.brightcanopy.com
paginate:         1
baseurl:          http://brightcanopy.github.io/blog.
author:
  name:           Bill Glover
  url:            https://twitter.com/BrightCanopyApp
  email:          bill@brightcanopy.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/BrightCanopy/blog
